Refractor Models to Freezed
KenyaFlutterDev/flutter_ke pull request #40
Opened 2023-09-28 10:20 UTC by Denzel101

## Description

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-10-05 19:50 UTC, mboyamike requested changes
We won't really need get_it since all the service location will be handled by riverpod. Removing the dependency should work fine

Also, just make the changes on the same branch and commit. I'll be able to see the changes in the pull request. No need to create a new pull request with the updated changes

2023-10-05 19:50 UTC, mboyamike commented on mobile/pubspec.yaml
When using riverpod, we won't really need get_it. All the service location can be done by riverpod

2023-10-05 19:50 UTC, mboyamike commented on mobile/lib/utils/locator.dart
We'll use riverpod to inject the AuthRepository throughout the app. So I would also remove these lines

2023-10-05 19:50 UTC, mboyamike commented on mobile/lib/auth/domain/repositories/auth_repository.dart
Looks good to me

2023-10-05 19:50 UTC, mboyamike commented on mobile/lib/auth/data/models/user_model.dart
Looks good to me

2023-12-14 18:41 UTC, mboyamike approved these changes

2023-12-14 18:41 UTC, merged

2023-12-14 18:49 UTC, mboyamike commented
Thanks for this

2023-12-20 15:37 UTC, Denzel-DM commented
Don't mention it. You can close the issue now. If you need more help don't hesitate to reach out 🤙